#!/usr/bin/env bats
# Tests for scripts/install.sh and scripts/uninstall.sh

load test_helper

# ---------------------------------------------------------------------------
# Cycle 1.2 — install.sh: help and dry-run
# ---------------------------------------------------------------------------

@test "install.sh --help exits 0 and shows usage" {
  run bash "$SCRIPTS_DIR/install.sh" --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"Usage"* ]]
  [[ "$output" == *"--dry-run"* ]]
}

@test "install.sh --dry-run prints DRY-RUN banner and exits 0" {
  mock_install_prereqs

  run bash "$SCRIPTS_DIR/install.sh" --dry-run
  [ "$status" -eq 0 ]
  [[ "$output" == *"DRY-RUN"* ]]
}

@test "install.sh --dry-run does not write any files to HOME" {
  mock_install_prereqs

  run bash "$SCRIPTS_DIR/install.sh" --dry-run

  # Binaries must not be created
  [ ! -f "$TMP_HOME/.local/bin/token-diet" ]
  [ ! -f "$TMP_HOME/.local/bin/token-diet-dashboard" ]
}

# ---------------------------------------------------------------------------
# Cycle 3.1 — uninstall.sh: dry-run skeleton
# ---------------------------------------------------------------------------

@test "uninstall.sh --dry-run exits 0" {
  run bash "$SCRIPTS_DIR/uninstall.sh" --dry-run
  [ "$status" -eq 0 ]
  [[ "$output" == *"dry-run"* ]]
}

@test "uninstall.sh --dry-run does not remove any files" {
  # Plant a binary that should survive dry-run
  echo "#!/bin/bash" > "$TMP_HOME/.local/bin/token-diet"
  chmod +x "$TMP_HOME/.local/bin/token-diet"

  run bash "$SCRIPTS_DIR/uninstall.sh" --dry-run --force

  # File must still exist after dry-run
  [ -f "$TMP_HOME/.local/bin/token-diet" ]
}

# ---------------------------------------------------------------------------
# Cycle 3.2 — uninstall.sh: binary removal
# ---------------------------------------------------------------------------

@test "uninstall.sh --force removes token-diet binary" {
  echo "#!/bin/bash" > "$TMP_HOME/.local/bin/token-diet"
  chmod +x "$TMP_HOME/.local/bin/token-diet"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force

  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.local/bin/token-diet" ]
}

@test "uninstall.sh --force removes token-diet-dashboard binary" {
  echo "#!/bin/bash" > "$TMP_HOME/.local/bin/token-diet-dashboard"
  chmod +x "$TMP_HOME/.local/bin/token-diet-dashboard"
  echo "#!/bin/bash" > "$TMP_HOME/.local/bin/token-diet-mcp"
  chmod +x "$TMP_HOME/.local/bin/token-diet-mcp"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force

  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.local/bin/token-diet-dashboard" ]
  [ ! -f "$TMP_HOME/.local/bin/token-diet-mcp" ]
}

@test "uninstall.sh --force removes the Serena launcher install writes to \$HOME/.local/bin/serena" {
  # install.sh install_serena generates a launcher wrapper at $HOME/.local/bin/serena
  # (uvx- or docker-runtime). It is NOT a cargo symlink, so `cargo uninstall`
  # never touches it — earlier uninstall removed rtk/tilth/icm but orphaned this
  # one (install/uninstall asymmetry). Plant the launcher exactly as install
  # writes it, then assert uninstall removes it.
  cat > "$TMP_HOME/.local/bin/serena" << 'WRAP'
#!/usr/bin/env bash
# token-diet Serena launcher (uvx runtime) — generated by install.sh
exec uvx --from "git+https://github.com/artificemachine/serena@deadbeef" serena start-mcp-server "$@"
WRAP
  chmod +x "$TMP_HOME/.local/bin/serena"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force

  [ "$status" -eq 0 ]
  [ ! -e "$TMP_HOME/.local/bin/serena" ]
}

@test "install --serena-only pins the Serena git ref (no bare git+serena) in vscode/opencode/cowork configs" {
  # FIX 2: three registration sites (VS Code template, OpenCode online, Cowork
  # online) previously emitted an UNPINNED git+<repo> ref, floating to upstream
  # HEAD instead of the audited fork revision. They must now emit the same pinned
  # git+<repo>@<rev> as SERENA_SRC (SERENA_REV = the superproject gitlink SHA).
  local sha
  sha="$(git -C "$PROJECT_ROOT" rev-parse "HEAD:forks/serena" 2>/dev/null || true)"
  [ -n "$sha" ]   # meaningful only inside the git checkout with submodule pinned

  mock_install_prereqs
  # git: route rev-parse to REAL git (needed for the pin) but stub submodule +
  # --version so ensure_git neither fetches nor prints a real version.
  local real_git; real_git="$(PATH="${PATH#"$TMP_BIN:"}" command -v git)"
  cat > "$TMP_BIN/git" << MOCK
#!/usr/bin/env bash
for a in "\$@"; do [ "\$a" = "submodule" ] && exit 0; done
case "\$1" in
  --version) echo "git version 2.50.0-mock"; exit 0 ;;
  *) exec "$real_git" "\$@" ;;
esac
MOCK
  chmod +x "$TMP_BIN/git"

  mock_cmd code       # HAS_VSCODE
  mock_cmd opencode   # HAS_OPENCODE
  # HAS_COWORK: COWORK_CFG must exist. resolve_cowork_cfg() checks the macOS
  # path's existence before the Linux path REGARDLESS of uname, so planting
  # both (as an earlier version of this test did) makes install.sh pick the
  # macOS path on every OS while a naive uname-based read assertion still
  # switches to the Linux path on Linux — a mismatch that only surfaces in
  # Linux CI. Plant only the OS-appropriate path, matching the existing
  # "malformed cowork config" test's pattern above.
  local cowork_dir
  if [ "$(uname -s)" = "Darwin" ]; then
    cowork_dir="$TMP_HOME/Library/Application Support/Claude"
  else
    cowork_dir="$TMP_HOME/.config/Claude"
  fi
  mkdir -p "$cowork_dir"
  echo '{}' > "$cowork_dir/claude_desktop_config.json"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode,vscode,cowork
  [ "$status" -eq 0 ]

  local vscode="$TMP_HOME/.config/token-diet/vscode-mcp.template.json"
  local opencode="$TMP_HOME/.config/opencode/opencode.json"
  local cowork="$cowork_dir/claude_desktop_config.json"

  [ -f "$vscode" ]
  [ -f "$opencode" ]
  [ -f "$cowork" ]

  local expected="git+https://github.com/artificemachine/serena@$sha"
  run python3 - "$vscode" "$opencode" "$cowork" "$expected" << 'PY'
import json, sys
expected = sys.argv[4]
vs = json.load(open(sys.argv[1]))["servers"]["serena"]["args"]
oc = json.load(open(sys.argv[2]))["mcp"]["serena"]["command"]
cw = json.load(open(sys.argv[3]))["mcpServers"]["serena"]["args"]
for label, arr in (("vscode", vs), ("opencode", oc), ("cowork", cw)):
    assert expected in arr, f"{label}: pinned ref {expected!r} not in {arr!r}"
    for a in arr:
        if isinstance(a, str) and a.startswith("git+") and "serena" in a:
            assert "@" in a, f"{label}: bare unpinned ref {a!r}"
print("OK")
PY
  [ "$status" -eq 0 ]
  [[ "$output" == *"OK"* ]]
}

# ---------------------------------------------------------------------------
# Cycle 3.3 — uninstall.sh: MCP JSON removal
# ---------------------------------------------------------------------------

@test "uninstall.sh removes tilth, serena and icm from claude-code settings.json" {
  mock_mcp_config claude-code tilth
  mock_mcp_config claude-code serena
  mock_mcp_config claude-code icm

  run bash "$SCRIPTS_DIR/uninstall.sh" --force

  [ "$status" -eq 0 ]
  # Keys should be gone from the JSON
  python3 - "$TMP_HOME/.claude/settings.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
servers = d.get("mcpServers", {})
assert "tilth"  not in servers, "tilth still present"
assert "serena" not in servers, "serena still present"
assert "icm"    not in servers, "icm still present"
PY
}

# ---------------------------------------------------------------------------
# Cycle 3.5 — uninstall.sh: doc file removal
# ---------------------------------------------------------------------------

@test "uninstall.sh removes token-diet.md from claude and codex dirs" {
  echo "# token-diet" > "$TMP_HOME/.claude/token-diet.md"
  echo "# token-diet" > "$TMP_HOME/.codex/token-diet.md"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force

  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.claude/token-diet.md" ]
  [ ! -f "$TMP_HOME/.codex/token-diet.md" ]
}

# ---------------------------------------------------------------------------
# Cycle 3.6 — uninstall.sh: serena memories preserved by default
# ---------------------------------------------------------------------------

@test "uninstall.sh preserves serena memories without --include-data" {
  mkdir -p "$TMP_HOME/.serena/memories"
  echo "memory" > "$TMP_HOME/.serena/memories/test.md"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force

  [ "$status" -eq 0 ]
  [ -f "$TMP_HOME/.serena/memories/test.md" ]
}

@test "uninstall.sh removes serena memories with --include-data" {
  mkdir -p "$TMP_HOME/.serena/memories"
  echo "memory" > "$TMP_HOME/.serena/memories/test.md"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force --include-data

  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.serena/memories/test.md" ]
}

# ---------------------------------------------------------------------------
# Cycle 4.1 — install.sh: --verbose flag accepted
# ---------------------------------------------------------------------------

@test "install.sh --verbose is accepted (not Unknown option)" {
  mock_install_prereqs

  run bash "$SCRIPTS_DIR/install.sh" --verbose --dry-run
  [ "$status" -eq 0 ]
  [[ "$output" != *"Unknown option"* ]]
}

@test "install.sh --verbose --dry-run prints full output (no tail truncation)" {
  mock_install_prereqs

  run bash "$SCRIPTS_DIR/install.sh" --verbose --dry-run
  [ "$status" -eq 0 ]
  # With --verbose, the DRY-RUN banner must appear (basic sanity)
  [[ "$output" == *"DRY-RUN"* ]]
}

@test "install.sh --help mentions --verbose" {
  run bash "$SCRIPTS_DIR/install.sh" --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"--verbose"* ]]
}

@test "install.sh --verify warns when Codex tilth MCP path is stale" {
  mock_cmd_with_gain
  mock_cmd tilth
  mock_cmd uv
  mock_cmd codex
  mock_mcp_config codex tilth "/missing/tilth"

  run bash "$SCRIPTS_DIR/install.sh" --verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"Codex tilth MCP command missing: /missing/tilth"* ]]
}

@test "install.sh --verify: stale single-quoted TOML path is flagged" {
  mock_cmd_with_gain
  mock_cmd tilth
  mock_cmd uv
  mock_cmd codex
  mkdir -p "$TMP_HOME/.codex"
  printf '\n[mcp_servers.tilth]\ncommand = '"'"'/missing/tilth'"'"'\n' >> "$TMP_HOME/.codex/config.toml"

  run bash "$SCRIPTS_DIR/install.sh" --verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"Codex tilth MCP command missing: /missing/tilth"* ]]
}

@test "install.sh --verify warns when Codex serena MCP path is stale" {
  mock_cmd_with_gain
  mock_cmd tilth
  mock_cmd uv
  mock_cmd codex
  mock_mcp_config codex serena "/missing/serena"

  run bash "$SCRIPTS_DIR/install.sh" --verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"Codex serena MCP command missing: /missing/serena"* ]]
}

@test "install.sh --verify warns when Codex icm MCP path is stale" {
  mock_cmd_with_gain
  mock_cmd tilth
  mock_cmd uv
  mock_cmd codex
  mock_icm
  mock_mcp_config codex icm "/missing/icm"

  run bash "$SCRIPTS_DIR/install.sh" --verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"Codex icm MCP command missing: /missing/icm"* ]]
}

# ---------------------------------------------------------------------------
# Cycle 5.1 — reinstall idempotency: opencode JSON
# ---------------------------------------------------------------------------

@test "install: --serena-only --hosts opencode does not duplicate serena entry on second run" {
  mock_install_prereqs
  mock_cmd opencode
  echo '{}' > "$TMP_HOME/.opencode.json"

  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode
  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
servers = d.get("mcp", {})
count = sum(1 for k in servers if "serena" in k.lower())
assert count == 1, f"Expected 1 serena entry, got {count}: {list(servers.keys())}"
PY
}

# ---------------------------------------------------------------------------
# Cycle 5.x — Strict Installation Decoupling: MCP configs must never reference
# the cloned source repo. Regression for the forks/-path leak that broke
# serena + tilth after moving/renaming the token-diet checkout.
# ---------------------------------------------------------------------------

@test "install: opencode MCP config never contains absolute forks/ paths" {
  mock_install_prereqs
  mock_cmd opencode
  echo '{}' > "$TMP_HOME/.opencode.json"

  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys, re
d = json.load(open(sys.argv[1]))
servers = d.get("mcp", {}) or d.get("mcpServers", {})
bad = re.compile(r"(^|/)forks/")
for name, entry in servers.items():
    cmd = entry.get("command") or entry.get("args") or []
    if isinstance(cmd, str):
        cmd = [cmd]
    flat = " ".join(str(x) for x in cmd)
    assert not bad.search(flat), (
        f"Install-decoupling leak: mcp.{name}.command contains a forks/ "
        f"path: {flat!r}. MCP configs must use bare commands + XDG-stable "
        f"launchers (see CLAUDE.md §Strict Installation Decoupling)."
    )
PY
}

@test "install: opencode tilth MCP entry uses --mcp subcommand (not bare mcp)" {
  mock_install_prereqs
  mock_cmd opencode
  echo '{}' > "$TMP_HOME/.opencode.json"

  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
t = (d.get("mcp") or {}).get("tilth") or {}
cmd = t.get("command") or []
flat = cmd if isinstance(cmd, str) else " ".join(str(x) for x in cmd)
assert "--mcp" in flat, f"tilth MCP command must include --mcp; got: {flat!r}"
# Negative assertion: the old bug was the bare positional `mcp` arg.
parts = cmd if isinstance(cmd, list) else cmd.split()
assert "mcp" not in parts or "--mcp" in parts, (
    f"tilth command has bare 'mcp' instead of '--mcp': {flat!r}"
)
PY
}

@test "install: opencode serena MCP entry uses 'serena start-mcp-server' (not nonexistent 'serena-mcp-server')" {
  mock_install_prereqs
  mock_cmd opencode
  echo '{}' > "$TMP_HOME/.opencode.json"

  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
s = (d.get("mcp") or {}).get("serena") or {}
cmd = s.get("command") or []
flat = cmd if isinstance(cmd, str) else " ".join(str(x) for x in cmd)
assert "serena-mcp-server" not in flat, (
    f"Serena's MCP entry point is 'serena start-mcp-server' — there is no "
    f"'serena-mcp-server' binary in the venv. Got: {flat!r}"
)
assert "start-mcp-server" in flat, f"Expected start-mcp-server in {flat!r}"
PY
}

@test "install: install.sh source no longer contains the serena-mcp-server (nonexistent binary) name" {
  # Static-source regression for the historical bug: install.sh used to write
  # "$PROJECT_ROOT/forks/serena/.venv/bin/serena-mcp-server" into MCP configs.
  # That binary never existed — Serena's entry point is `serena`, which
  # dispatches `start-mcp-server`. Any reappearance of this string in the
  # installer source is a regression and must fail CI.
  ! grep -E "serena-mcp-server(\.exe)?(\"|')" "$SCRIPTS_DIR/install.sh" \
    || { echo "LEAK: install.sh still references the nonexistent serena-mcp-server binary"; false; }
  ! grep -E "serena-mcp-server(\.exe)?(\"|')" "$SCRIPTS_DIR/Install.ps1" \
    || { echo "LEAK: Install.ps1 still references the nonexistent serena-mcp-server binary"; false; }
}

@test "install: --serena-only preserves unrelated mcp entries in opencode config" {
  mock_install_prereqs
  mock_cmd opencode
  python3 -c "
import json
with open('$TMP_HOME/.opencode.json', 'w') as f:
    json.dump({'mcp': {'other-tool': {'type': 'local', 'command': ['other'], 'enabled': True}}}, f)
    f.write('\n')
"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
servers = d.get("mcp", {})
assert "other-tool" in servers, f"Unrelated entry was removed: {list(servers.keys())}"
assert "serena" in servers, f"Serena entry missing: {list(servers.keys())}"
PY
}

# ---------------------------------------------------------------------------
# Cycle 5.2 — malformed JSON is preserved, not overwritten: opencode
# ---------------------------------------------------------------------------

@test "install: --serena-only aborts and preserves a malformed opencode config (backs up, no stub)" {
  mock_install_prereqs
  mock_cmd opencode
  # Malformed JSON — the installer must refuse to overwrite it with a fresh stub.
  printf '{"broken json\n' > "$TMP_HOME/.opencode.json"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode
  # Safer contract: abort loudly instead of destroying existing (if broken) config.
  [ "$status" -ne 0 ]
  [[ "$output" == *"malformed JSON"* ]]

  # Original file is left untouched (NOT replaced with a fresh {serena} stub)...
  grep -q "broken json" "$TMP_HOME/.opencode.json"

  # ...and a timestamped .corrupt-* backup was written capturing it.
  local n
  n=$(ls "$TMP_HOME"/.opencode.json.corrupt-* 2>/dev/null | wc -l | tr -d ' ')
  [ "$n" -ge 1 ]
}

# ---------------------------------------------------------------------------
# Cycle 5.3 — malformed JSON is preserved, not overwritten: cowork (Claude Desktop)
# ---------------------------------------------------------------------------

@test "install: --serena-only aborts and preserves a malformed cowork config (backs up, no stub)" {
  mock_install_prereqs
  mock_cmd opencode  # also detect opencode so --hosts cowork filter has >1 choice to filter

  # Create malformed cowork config so HAS_COWORK=true and the json.load site is hit
  local cowork_dir
  if [ "$(uname -s)" = "Darwin" ]; then
    cowork_dir="$TMP_HOME/Library/Application Support/Claude"
  else
    cowork_dir="$TMP_HOME/.config/Claude"
  fi
  mkdir -p "$cowork_dir"
  printf '{"broken json\n' > "$cowork_dir/claude_desktop_config.json"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts cowork
  # Safer contract: abort loudly instead of destroying existing (if broken) config.
  [ "$status" -ne 0 ]
  [[ "$output" == *"malformed JSON"* ]]

  # Original file is left untouched (NOT replaced with a fresh {serena} stub)...
  grep -q "broken json" "$cowork_dir/claude_desktop_config.json"

  # ...and a timestamped .corrupt-* backup was written capturing it.
  local n
  n=$(ls "$cowork_dir"/claude_desktop_config.json.corrupt-* 2>/dev/null | wc -l | tr -d ' ')
  [ "$n" -ge 1 ]
}

# ---------------------------------------------------------------------------
# Cycle 5.4 — uninstall idempotency
# ---------------------------------------------------------------------------

@test "uninstall: --force is idempotent (second run on clean system exits 0)" {
  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]
}

# ---------------------------------------------------------------------------
# Cycle 6.2 — modifier-only flags must not suppress install (v1.6.1, issue #38)
# ---------------------------------------------------------------------------

@test "install.sh --skip-tests (modifier-only) still triggers Serena MCP + opencode rules" {
  mock_install_prereqs
  mock_cmd opencode
  mkdir -p "$TMP_HOME/.config/opencode"
  echo '{}' > "$TMP_HOME/.config/opencode/opencode.json"

  # Wizard answers: install-all=y, dedup=y, local-mode=n (use uvx path — no Docker).
  # Pre-fix: --skip-tests set has_args=true, wizard was skipped, do_serena stayed
  # false, injection never ran. Post-fix: has_args stays false for modifier-only
  # flags, wizard runs, install proceeds normally.
  # Wizard prompts: install-all, dedup, local-mode, proceed.
  run bash -c "printf 'y\ny\nn\ny\n' | bash '$SCRIPTS_DIR/install.sh' --skip-tests --hosts opencode"
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
p = d.get("mode", {}).get("build", {}).get("prompt", "")
assert "token-diet:begin" in p, "OpenCode rules not injected — modifier-only flag bypassed install"
PY
}

# ---------------------------------------------------------------------------
# Cycle 6.1 — OpenCode prompt rule injection (v1.6.0)
# ---------------------------------------------------------------------------

@test "install.sh injects token-diet rules into opencode mode.build.prompt and mode.plan.prompt" {
  mock_install_prereqs
  mock_cmd opencode
  mkdir -p "$TMP_HOME/.config/opencode"
  echo '{}' > "$TMP_HOME/.config/opencode/opencode.json"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
for m in ("build", "plan"):
    p = d.get("mode", {}).get(m, {}).get("prompt", "")
    assert "token-diet:begin" in p, f"mode.{m}.prompt missing begin marker"
    assert "token-diet:end"   in p, f"mode.{m}.prompt missing end marker"
    assert "tilth_search"     in p, f"mode.{m}.prompt missing tilth rules"
PY
}

@test "install.sh opencode rule injection is idempotent (no duplication on second run)" {
  mock_install_prereqs
  mock_cmd opencode
  mkdir -p "$TMP_HOME/.config/opencode"
  echo '{}' > "$TMP_HOME/.config/opencode/opencode.json"

  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode
  bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode

  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
for m in ("build", "plan"):
    p = d.get("mode", {}).get(m, {}).get("prompt", "")
    assert p.count("token-diet:begin") == 1, f"mode.{m}.prompt has duplicated begin markers"
    assert p.count("token-diet:end")   == 1, f"mode.{m}.prompt has duplicated end markers"
PY
}

@test "install.sh opencode rule injection preserves user's existing prompt text" {
  mock_install_prereqs
  mock_cmd opencode
  mkdir -p "$TMP_HOME/.config/opencode"
  python3 -c "
import json
with open('$TMP_HOME/.config/opencode/opencode.json', 'w') as f:
    json.dump({'mode': {'build': {'prompt': 'USER ORIGINAL BUILD PROMPT'}, 'plan': {'prompt': 'USER ORIGINAL PLAN PROMPT'}}}, f)
    f.write('\n')
"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts opencode
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
assert "USER ORIGINAL BUILD PROMPT" in d["mode"]["build"]["prompt"]
assert "USER ORIGINAL PLAN PROMPT"  in d["mode"]["plan"]["prompt"]
PY
}

@test "uninstall.sh strips token-diet block from opencode prompts but preserves user text" {
  mock_cmd opencode
  mkdir -p "$TMP_HOME/.config/opencode"
  python3 -c "
import json
prompt = 'USER TEXT\n<!-- token-diet:begin -->\nrules here\n<!-- token-diet:end -->\nTRAILING USER TEXT'
with open('$TMP_HOME/.config/opencode/opencode.json', 'w') as f:
    json.dump({'mode': {'build': {'prompt': prompt}, 'plan': {'prompt': prompt}}}, f)
    f.write('\n')
"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
for m in ("build", "plan"):
    p = d["mode"][m]["prompt"]
    assert "token-diet:begin" not in p, f"mode.{m} still has markers"
    assert "USER TEXT" in p, f"mode.{m} user text lost"
    assert "TRAILING USER TEXT" in p, f"mode.{m} trailing user text lost"
PY
}

# ---------------------------------------------------------------------------

@test "install.sh writes Serena to Linux Claude Desktop config when that config exists" {
  mock_install_prereqs
  mkdir -p "$TMP_HOME/.config/Claude"
  printf '{}\n' > "$TMP_HOME/.config/Claude/claude_desktop_config.json"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts cowork
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.config/Claude/claude_desktop_config.json" << 'PY'
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
servers = data.get("mcpServers", {})
assert "serena" in servers, "serena not written to Linux Claude Desktop config"
assert servers["serena"]["command"] == "uvx", servers["serena"]
assert "--project-from-cwd" in servers["serena"]["args"], servers["serena"]["args"]
PY
}

# ---------------------------------------------------------------------------
# install.sh: codex serena idempotency uses anchored TOML table header
# Regression guard: prior behavior used bare `grep -q "serena"` which
# false-matched stray orphan arrays containing the string "serena"
# (vestigial pasted args lines) and silently skipped the real registration.
# ---------------------------------------------------------------------------

@test "install.sh registers Serena in codex config when only a stray 'serena' substring exists" {
  mock_install_prereqs
  mock_cmd codex
  # Config has NO real [mcp_servers.serena] block but a stray args line
  # containing "serena". The old bare-grep check treated this as
  # "already configured" and skipped real registration.
  cat > "$TMP_HOME/.codex/config.toml" << 'TOML'
[mcp_servers.tilth]
command = "/some/path/tilth"
args = ["--mcp"]

# Vestigial orphan from a bad paste — contains the substring "serena"
["--from", "git+https://github.com/celstnblacc/serena", "serena", "start-mcp-server"]
TOML

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts codex
  [ "$status" -eq 0 ]

  # A real [mcp_servers.serena] table header must now be present on its own line
  grep -Eq '^\[mcp_servers\.serena\]' "$TMP_HOME/.codex/config.toml"
}

@test "install.sh does not duplicate Serena block when a real [mcp_servers.serena] header already exists" {
  mock_install_prereqs
  mock_cmd codex
  cat > "$TMP_HOME/.codex/config.toml" << 'TOML'
[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/celstnblacc/serena", "serena", "start-mcp-server", "--context=codex", "--headless", "--project-from-cwd"]
TOML

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --hosts codex
  [ "$status" -eq 0 ]

  local header_count
  header_count=$(grep -cE '^\[mcp_servers\.serena\]' "$TMP_HOME/.codex/config.toml")
  [ "$header_count" -eq 1 ]
}

# ---------------------------------------------------------------------------
# install.sh: ICM codex idempotency uses the same anchored TOML table header.
# The idempotency guard MUST be the exact line-anchored header ^\[mcp_servers\.icm\]
# — never a loose substring match on "icm" (which would false-match a stray
# args line and silently skip the real registration).
# ---------------------------------------------------------------------------

@test "install.sh registers ICM in codex config when only a stray 'icm' substring exists" {
  mock_install_prereqs
  mock_icm
  mock_cmd codex
  # Config has NO real [mcp_servers.icm] block but a stray args line
  # containing the substring "icm". A bare-grep guard would treat this as
  # "already configured" and skip the real registration.
  cat > "$TMP_HOME/.codex/config.toml" << 'TOML'
[mcp_servers.tilth]
command = "tilth"
args = ["--mcp"]

# Vestigial orphan from a bad paste — contains the substring "icm"
["--some-icm-flag", "serve"]
TOML

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --hosts codex
  [ "$status" -eq 0 ]

  # A real [mcp_servers.icm] table header must now be present on its own line
  grep -Eq '^\[mcp_servers\.icm\]' "$TMP_HOME/.codex/config.toml"
  # And the bare-PATH command is written — never a forks/ path
  grep -Eq '^command = "icm"' "$TMP_HOME/.codex/config.toml"
}

@test "install.sh does not duplicate ICM block when a real [mcp_servers.icm] header already exists" {
  mock_install_prereqs
  mock_icm
  mock_cmd codex
  cat > "$TMP_HOME/.codex/config.toml" << 'TOML'
[mcp_servers.icm]
command = "icm"
args = ["serve", "--compact"]
TOML

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --hosts codex
  [ "$status" -eq 0 ]

  local header_count
  header_count=$(grep -cE '^\[mcp_servers\.icm\]' "$TMP_HOME/.codex/config.toml")
  [ "$header_count" -eq 1 ]
}

# ---------------------------------------------------------------------------
# install.sh: OpenCode mcp.icm injection — bare-PATH command, idempotent.
# ---------------------------------------------------------------------------

@test "install.sh injects mcp.icm into opencode config with bare-PATH command" {
  mock_install_prereqs
  mock_icm
  mock_cmd opencode
  echo '{}' > "$TMP_HOME/.opencode.json"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --hosts opencode
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
mcp = d.get("mcp", {})
assert "icm" in mcp, f"icm not registered in opencode: {list(mcp.keys())}"
entry = mcp["icm"]
assert entry.get("type") == "local", entry
assert entry.get("command") == ["icm", "serve", "--compact"], entry
assert entry.get("enabled") is True, entry
PY
}

@test "install.sh opencode mcp.icm injection is idempotent (no duplication on second run)" {
  mock_install_prereqs
  mock_icm
  mock_cmd opencode
  echo '{}' > "$TMP_HOME/.opencode.json"

  bash "$SCRIPTS_DIR/install.sh" --icm-only --hosts opencode
  bash "$SCRIPTS_DIR/install.sh" --icm-only --hosts opencode

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
mcp = d.get("mcp", {})
count = sum(1 for k in mcp if "icm" in k.lower())
assert count == 1, f"Expected 1 icm entry, got {count}: {list(mcp.keys())}"
PY
}

@test "install.sh --icm-only preserves unrelated mcp entries in opencode config" {
  mock_install_prereqs
  mock_icm
  mock_cmd opencode
  python3 -c "
import json
with open('$TMP_HOME/.opencode.json', 'w') as f:
    json.dump({'mcp': {'other-tool': {'type': 'local', 'command': ['other'], 'enabled': True}}}, f)
    f.write('\n')
"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --hosts opencode
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.opencode.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
mcp = d.get("mcp", {})
assert "other-tool" in mcp, f"Unrelated entry was removed: {list(mcp.keys())}"
assert "icm" in mcp, f"icm entry missing: {list(mcp.keys())}"
PY
}

# ---------------------------------------------------------------------------
# Cycle 6 — docextract / ctxwarn context hooks (--with-context-hooks, opt-in)
# ---------------------------------------------------------------------------

@test "context hooks: not installed without --with-context-hooks" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  [ ! -d "$TMP_HOME/.local/bin/token-diet-hooks" ]
  [ ! -f "$TMP_HOME/.claude/settings.json" ]
}

@test "context hooks: --with-context-hooks registers both hooks into claude settings, preserving existing hooks" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  python3 -c "
import json
with open('$TMP_HOME/.claude/settings.json', 'w') as f:
    json.dump({'hooks': {'SessionStart': [{'matcher': '*', 'hooks': [{'type': 'command', 'command': 'echo unrelated', 'timeout': 5}]}]}}, f)
    f.write('\n')
"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.claude/settings.json" "$TMP_HOME" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
home = sys.argv[2]
hooks = d.get("hooks", {})

session_start = hooks.get("SessionStart", [])
assert any(h.get("command") == "echo unrelated" for e in session_start for h in e.get("hooks", [])), \
    "pre-existing SessionStart hook was lost"

pre = hooks.get("PreToolUse", [])
docextract_cmd = f"{home}/.local/bin/token-diet-hooks/docextract-pre-read.sh"
matched = [e for e in pre if e.get("matcher") == "Read"
           and any(h.get("command") == docextract_cmd for h in e.get("hooks", []))]
assert matched, f"docextract PreToolUse/Read hook missing: {pre}"

post = hooks.get("PostToolUse", [])
ctxwarn_cmd = f"{home}/.local/bin/token-diet-hooks/ctxwarn-post.sh"
matched = [e for e in post if e.get("matcher") == "*"
           and any(h.get("command") == ctxwarn_cmd for h in e.get("hooks", []))]
assert matched, f"ctxwarn PostToolUse/* hook missing: {post}"
PY
}

@test "context hooks: shims installed under .local/bin/token-diet-hooks, executable, no dev-checkout path" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude
  [ "$status" -eq 0 ]

  [ -x "$TMP_HOME/.local/bin/token-diet-hooks/docextract-pre-read.sh" ]
  [ -x "$TMP_HOME/.local/bin/token-diet-hooks/ctxwarn-post.sh" ]
  ! grep -q "$SCRIPTS_DIR" "$TMP_HOME/.local/bin/token-diet-hooks/docextract-pre-read.sh"
  ! grep -q "$SCRIPTS_DIR" "$TMP_HOME/.local/bin/token-diet-hooks/ctxwarn-post.sh"
}

@test "context hooks: idempotent — running install twice does not duplicate entries" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude
  [ "$status" -eq 0 ]
  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.claude/settings.json" "$TMP_HOME" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
home = sys.argv[2]
hooks = d.get("hooks", {})

docextract_cmd = f"{home}/.local/bin/token-diet-hooks/docextract-pre-read.sh"
ctxwarn_cmd = f"{home}/.local/bin/token-diet-hooks/ctxwarn-post.sh"

pre_count = sum(1 for e in hooks.get("PreToolUse", []) for h in e.get("hooks", []) if h.get("command") == docextract_cmd)
post_count = sum(1 for e in hooks.get("PostToolUse", []) for h in e.get("hooks", []) if h.get("command") == ctxwarn_cmd)
assert pre_count == 1, f"expected 1 docextract hook, found {pre_count}"
assert post_count == 1, f"expected 1 ctxwarn hook, found {post_count}"
PY
}

@test "context hooks: malformed settings.json aborts that host's registration without writing, install still exits 0" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  printf '{"broken json\n' > "$TMP_HOME/.claude/settings.json"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude
  [ "$status" -eq 0 ]

  grep -q "broken json" "$TMP_HOME/.claude/settings.json"
  ! grep -q "token-diet-hooks" "$TMP_HOME/.claude/settings.json"
}

@test "context hooks: non-claude harness gets awareness-docextract.md" {
  mock_install_prereqs
  mock_icm
  mock_cmd codex

  # Real `claude`/opencode/gemini binaries are on this dev machine's PATH, and
  # TMP_BIN only prepends (does not isolate) — --hosts restricts host wiring
  # to codex regardless of what else install.sh detects, matching the pattern
  # every other multi-host test in this file already uses.
  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts codex
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.codex/awareness-docextract.md" ]
  [ ! -f "$TMP_HOME/.claude/settings.json" ]
}

@test "context hooks: uninstall removes both hook entries and leaves unrelated hooks intact" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  python3 -c "
import json
with open('$TMP_HOME/.claude/settings.json', 'w') as f:
    json.dump({'hooks': {'SessionStart': [{'matcher': '*', 'hooks': [{'type': 'command', 'command': 'echo unrelated', 'timeout': 5}]}]}}, f)
    f.write('\n')
"
  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude
  [ "$status" -eq 0 ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  [ ! -d "$TMP_HOME/.local/bin/token-diet-hooks" ]
  python3 - "$TMP_HOME/.claude/settings.json" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
hooks = d.get("hooks", {})

session_start = hooks.get("SessionStart", [])
assert any(h.get("command") == "echo unrelated" for e in session_start for h in e.get("hooks", [])), \
    "unrelated SessionStart hook was removed"

for event in ("PreToolUse", "PostToolUse"):
    for e in hooks.get(event, []):
        for h in e.get("hooks", []):
            assert "token-diet-hooks" not in h.get("command", ""), f"hook entry not removed: {h}"
PY
}

# ---------------------------------------------------------------------------
# Cycle 6.1 — docextract pre-read shim: suffix passthrough policy
#
# Regression: the shim's intercepted-suffix set originally included .txt/.md,
# which caused two distinct problems:
#   1. .md: docextract's cache format is always .md, so reading a .md source
#      → extracts to a .md cache file → shim intercepts the .md cache → loops
#      forever. This is the live bug caught while writing the prior handoff.
#   2. .txt: already plain text, extracting adds a pointless round-trip.
# Both must pass through (exit 0). The real extraction targets (.pdf/.csv/
# .html/.htm) must still block (exit 2) so Claude reads the extracted cache.
# ---------------------------------------------------------------------------

@test "docextract shim: .md file passes through (exit 0, no block)" {
  mock_token_diet_extract

  local md="$TMP_HOME/HANDOFF.md"
  echo "# heading" > "$md"

  run bash "$PROJECT_ROOT/scripts/lib/hooks/docextract-pre-read.sh" \
    < <(printf '{"tool_input":{"file_path":"%s"}}' "$md")
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "docextract shim: .txt file passes through (exit 0, no block)" {
  mock_token_diet_extract

  local txt="$TMP_HOME/notes.txt"
  echo "plain text" > "$txt"

  run bash "$PROJECT_ROOT/scripts/lib/hooks/docextract-pre-read.sh" \
    < <(printf '{"tool_input":{"file_path":"%s"}}' "$txt")
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "docextract shim: .pdf file still intercepts (exit 2, redirects to cache)" {
  mock_token_diet_extract

  local pdf="$TMP_HOME/sample.pdf"
  printf '%%PDF-1.4 fake\n' > "$pdf"

  run bash "$PROJECT_ROOT/scripts/lib/hooks/docextract-pre-read.sh" \
    < <(printf '{"tool_input":{"file_path":"%s"}}' "$pdf")
  [ "$status" -eq 2 ]
  [[ "$output" == *"read that file instead"* ]]
}

# ---------------------------------------------------------------------------
# Cycle 6.2 — context hooks: OpenCode + Copilot wiring (verified 2026-07-19)
#
# Regression: prior to v1.14.5, OpenCode was silently excluded from context
# hooks (treated like Copilot — "no verified schema, awareness doc only").
# This was wrong: OpenCode HAS a documented TS plugin API with
# "tool.execute.before" / "tool.execute.after" events. v1.14.5 adds a real
# plugin under ~/.config/opencode/plugins/token-diet-hooks.ts and registers
# it in opencode.json's plugin array (idempotent merge).
#
# Copilot CLI: confirmed (via https://github.com/github/copilot-cli README)
# that v0.0.377 has NO hook surface — only custom agents / LSP / MCP. OQ-3
# resolved as: best we can do is awareness doc at ~/.copilot/. Awareness
# doc is now installed for Copilot too (previously skipped entirely).
# ---------------------------------------------------------------------------

@test "context hooks: --with-context-hooks installs OpenCode plugin + registers it in opencode.json (idempotent)" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  mock_cmd opencode
  mkdir -p "$TMP_HOME/.config/opencode/plugins"

  # Pre-existing opencode.json with an unrelated plugin entry — exercise the
  # "merge into existing array, don't drop other plugins" path.
  cat > "$TMP_HOME/.config/opencode/opencode.json" << 'JSON'
{
  "mcp": {},
  "plugin": ["./plugins/other.ts"]
}
JSON

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude,opencode
  [ "$status" -eq 0 ]

  # Plugin file exists, mode 644
  [ -f "$TMP_HOME/.config/opencode/plugins/token-diet-hooks.ts" ]
  local mode
  mode=$(stat -c '%a' "$TMP_HOME/.config/opencode/plugins/token-diet-hooks.ts" 2>/dev/null || stat -f '%Lp' "$TMP_HOME/.config/opencode/plugins/token-diet-hooks.ts")
  [ "$mode" = "644" ]

  # Plugin source matches what we ship
  diff "$TMP_HOME/.config/opencode/plugins/token-diet-hooks.ts" "$PROJECT_ROOT/scripts/lib/hooks-plugins/opencode.ts"

  # opencode.json: other plugin preserved, ours appended (relative path)
  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
plugins = d.get("plugin", [])
assert isinstance(plugins, list), f"plugin should be a list, got {type(plugins)}"
assert "./plugins/other.ts" in plugins, f"pre-existing plugin dropped: {plugins}"
assert "plugins/token-diet-hooks.ts" in plugins, f"new plugin not registered: {plugins}"
PY

  # Idempotent — second run does NOT add a duplicate entry
  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts claude,opencode
  [ "$status" -eq 0 ]
  python3 - "$TMP_HOME/.config/opencode/opencode.json" << 'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
plugins = d.get("plugin", [])
n = plugins.count("plugins/token-diet-hooks.ts")
assert n == 1, f"expected exactly 1 entry, found {n}: {plugins}"
PY
}

@test "context hooks: --with-context-hooks writes awareness-docextract.md to ~/.copilot (OQ-3 resolved)" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  # Detector checks both `github-copilot-cli` (legacy Homebrew) and `copilot`
  # (current npm @github/copilot). Mock the npm form to prove both work.
  mock_cmd copilot
  mkdir -p "$TMP_HOME/.copilot"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts copilot
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.copilot/awareness-docextract.md" ]
}

@test "context hooks: Copilot CLI detector also accepts the legacy github-copilot-cli name" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  # Legacy Homebrew binary name. The v1.14.5 detector checks both names
  # because some users (like this one) have only `copilot` from npm while
  # others have only `github-copilot-cli` from Homebrew — silent misses
  # are exactly what we're guarding against.
  mock_cmd github-copilot-cli
  mkdir -p "$TMP_HOME/.copilot"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts copilot
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.copilot/awareness-docextract.md" ]
}

@test "context hooks: opencode plugin source contains both hook handlers (docextract + ctxwarn)" {
  # Pure source-level check: the shipped plugin must wire both events.
  # Catches regressions where one handler gets accidentally removed.
  local src="$PROJECT_ROOT/scripts/lib/hooks-plugins/opencode.ts"
  [ -f "$src" ]
  grep -q '"tool.execute.before"' "$src"
  grep -q '"tool.execute.after"'  "$src"
  # Must extract via token-diet (not native parser)
  grep -q 'token-diet extract'      "$src"
  # Must mirror ctxwarn band logic (estimate / threshold / band file)
  grep -qE 'DEFAULT_CTX_THRESHOLD|ctx_threshold' "$src"
}

# ---------------------------------------------------------------------------
# Cycle 6.3 — context hooks: Gemini CLI real hooks (OQ-2 resolved, 2026-07-19)
#
# Gemini CLI v0.49.0 (`gemini hooks migrate --from-claude`) confirms that
# its hook schema is identical to Claude Code's ~/.claude/settings.json
# JSON format with one difference: tool names are mapped (Read→read_file,
# Bash→run_shell_command, Edit→replace, etc.) via TOOL_NAME_MAPPING in the
# bundle. The migrate implementation in gemini-APNDCIQH.js proves the JSON
# structure is compatible — same hooks key, same matcher/hooks/type/command/
# timeout fields, same event names (PreToolUse, PostToolUse, SessionEnd,
# PreCompact, Notification).
#
# We register docextract with matcher "read_file" (not "Read" — Gemini
# maps the tool name) and ctxwarn with matcher "*" (universal, no mapping).
# Awareness doc is still written as a courtesy fallback.
# ---------------------------------------------------------------------------

@test "context hooks: --with-context-hooks registers both hooks into gemini settings (read_file matcher)" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  mock_cmd opencode
  mock_gemini  # writes $HOME/.gemini/settings.json with empty mcpServers

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts gemini
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.gemini/settings.json" "$TMP_HOME" << 'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
home = sys.argv[2]
hooks = d.get("hooks", {})

pre = hooks.get("PreToolUse", [])
docextract_cmd = f"{home}/.local/bin/token-diet-hooks/docextract-pre-read.sh"
matched = [e for e in pre if e.get("matcher") == "read_file"
           and any(h.get("command") == docextract_cmd for h in e.get("hooks", []))]
assert matched, f"docextract PreToolUse/read_file hook missing: {pre}"

post = hooks.get("PostToolUse", [])
ctxwarn_cmd = f"{home}/.local/bin/token-diet-hooks/ctxwarn-post.sh"
matched = [e for e in post if e.get("matcher") == "*"
           and any(h.get("command") == ctxwarn_cmd for h in e.get("hooks", []))]
assert matched, f"ctxwarn PostToolUse/* hook missing: {post}"
PY
}

@test "context hooks: Gemini CLI uses read_file matcher, NOT Read (tool name mapping verified)" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  mock_cmd opencode
  mock_gemini

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts gemini
  [ "$status" -eq 0 ]

  python3 - "$TMP_HOME/.gemini/settings.json" << 'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
pre = d.get("hooks", {}).get("PreToolUse", [])
# Must use gemini-mapped "read_file", not Claude Code's "Read"
for e in pre:
    assert e.get("matcher") != "Read", (
        f"wrong matcher: expected read_file, got {e.get('matcher')}. "
        f"Gemini CLI maps tool names via TOOL_NAME_MAPPING (Read -> read_file)"
    )
PY
}

@test "context hooks: Gemini awareness-doc still written as courtesy fallback" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  mock_cmd opencode
  mock_gemini
  mkdir -p "$TMP_HOME/.gemini"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only --with-context-hooks --hosts gemini
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.gemini/awareness-docextract.md" ]
}

# ---------------------------------------------------------------------------
# Cycle 7 — installed token-diet's Python cores (extract / budget --check)

# ---------------------------------------------------------------------------
# Cycle 7 — installed token-diet's Python cores (extract / budget --check)
#
# Regression: cmd_extract / cmd_budget --check shell out to
# $SCRIPT_DIR/lib/<name>.py. Every other test in this file (and every
# real-machine validation up to this point) ran token-diet FROM the repo
# checkout, where scripts/lib/ is a sibling directory — so this always
# resolved and the bug was invisible. Once installed to .local/bin, the
# installed copy's own SCRIPT_DIR became .local/bin, and its lib/ was
# never copied there, breaking both subcommands post-install. Found by a
# live `install.sh --with-context-hooks` run against a real HOME.
# ---------------------------------------------------------------------------

@test "install: Python cores (docextract/tdcache/ctxwarn) are copied to .local/bin/lib" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.local/bin/lib/docextract.py" ]
  [ -f "$TMP_HOME/.local/bin/lib/tdcache.py" ]
  [ -f "$TMP_HOME/.local/bin/lib/ctxwarn.py" ]
}

@test "install: the INSTALLED token-diet binary (not the repo checkout) can run extract and budget --check" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  local sample="$TMP_HOME/sample.txt"
  echo "installed-binary smoke test" > "$sample"

  run "$TMP_HOME/.local/bin/token-diet" extract "$sample"
  [ "$status" -eq 0 ]
  [[ "$output" == *"/.cache/token-diet/extract/"* ]]

  local jsonl="$TMP_HOME/transcript.jsonl"
  python3 -c "import json; print(json.dumps({'content': 'short'}))" > "$jsonl"
  run "$TMP_HOME/.local/bin/token-diet" budget --check --transcript "$jsonl"
  [ "$status" -eq 0 ]
}

@test "uninstall: removes .local/bin/lib" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]
  [ -d "$TMP_HOME/.local/bin/lib" ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]
  [ ! -d "$TMP_HOME/.local/bin/lib" ]
}

# ---------------------------------------------------------------------------
# Cycle 8 — Phase 5 Iteration 1: shared shell lib ships with the installed binary
#
# Strict Installation Decoupling (CLAUDE.md): once installed, token-diet runs
# from $HOME/.local/bin and cannot source anything from the repo checkout. Any
# shared shell lib must therefore be copied to $bin_dir/lib/ alongside the
# Python cores. The v1.14.0 cmd_extract break happened because the copy
# manifest was hardcoded and a newly-added core was omitted — tests passed from
# the dev checkout, the installed binary was broken for every user. The glob
# test below is the negative test for that failure mode.
# ---------------------------------------------------------------------------

@test "install: shell lib (hosts.sh) is copied to .local/bin/lib" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.local/bin/lib/hosts.sh" ]
}

@test "install: shell-lib copy is glob-based, not a hardcoded manifest" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  # Planted input: a lib file the installer has never heard of. A hardcoded
  # manifest silently skips it — exactly the v1.14.0 failure mode.
  local planted="$SCRIPTS_DIR/lib/zz-planted-negative-test.sh"
  echo '# planted by tests/install.bats' > "$planted"

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  local st="$status"
  rm -f "$planted"

  [ "$st" -eq 0 ]
  [ -f "$TMP_HOME/.local/bin/lib/zz-planted-negative-test.sh" ]
}

@test "uninstall: removes the installed shell lib" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]
  [ -f "$TMP_HOME/.local/bin/lib/hosts.sh" ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.local/bin/lib/hosts.sh" ]
}

# ---------------------------------------------------------------------------
# Cycle 9 — release.sh survives a clean working tree
#
# release.sh exited 1 silently, always, whenever `git status --porcelain` was
# empty. The unstaged-count pipeline starts with `grep -v`, which exits 1 when
# it selects no lines; under `set -euo pipefail` (line 15) that failure reaches
# the bare assignment and set -e kills the script with no message.
#
# A clean tree is the PRECONDITION for tagging a release, so every real
# invocation hit this and every casual dev run did not. Nothing past preflight
# had ever executed. Same mechanism as the v1.15.x defect family: code never
# executed in the condition it was written for.
# ---------------------------------------------------------------------------

@test "release.sh --dry-run exits 0 on a clean working tree" {
  # The bug only fires when `git status --porcelain` is EMPTY, and a clean tree
  # is the precondition a real release runs under. Rather than shim git or
  # depend on the dev checkout being clean (writing this test dirties it) or on
  # submodules being present (CI checks out without them), build a throwaway
  # repo: release.sh derives ROOT from its own location, so a copy with stub
  # forks and a genuinely clean tree exercises the real script hermetically.
  local repo="$TMP_HOME/relrepo"
  mkdir -p "$repo/scripts" "$repo/forks"/{rtk,tilth,serena,icm}
  cp "$SCRIPTS_DIR/release.sh" "$repo/scripts/release.sh"
  # release.sh reads TD_VERSION out of scripts/token-diet as its single source
  # of truth and hard-exits if it cannot parse one.
  echo 'readonly TD_VERSION="9.9.9"' > "$repo/scripts/token-diet"
  # `ls -A` must see something, or preflight fails on "fork is empty" first.
  local f
  for f in rtk tilth serena icm; do echo "stub" > "$repo/forks/$f/.keep"; done

  git -C "$repo" init -q
  git -C "$repo" config user.email test@example.com
  git -C "$repo" config user.name test
  git -C "$repo" add -A
  # core.hooksPath is set globally on this machine and blocks commits to main;
  # the throwaway repo wants none of that policy.
  git -C "$repo" -c core.hooksPath=/dev/null commit -qm "stub" --no-gpg-sign

  # Precondition now genuinely holds, and is asserted rather than assumed.
  run git -C "$repo" status --porcelain
  [ -z "$output" ]

  mock_cmd cargo
  mock_cmd uv
  mock_cmd gh

  run bash "$repo/scripts/release.sh" --dry-run --sign-only
  [ "$status" -eq 0 ]
}

@test "release.sh preflight checks all four forks, including icm" {
  # The submodule loop listed rtk/tilth/serena only. There are four forks, not
  # three — the same omission the v1.15.4 tag-message fix corrected elsewhere.
  run grep -nE 'for fork in .*icm' "$SCRIPTS_DIR/release.sh"
  [ "$status" -eq 0 ]
}

@test "install: the INSTALLED token-diet-install.sh can source the host registry" {
  # install.sh is itself installed as token-diet-install.sh, so its SCRIPT_DIR
  # becomes the bin dir and `source $SCRIPT_DIR/lib/hosts.sh` resolves to the
  # INSTALLED lib, not the repo one. If Iteration 1's copy step regresses, the
  # installed installer dies at its first source line. This is the v1.14.0
  # failure mode aimed at the installer itself.
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  [ -f "$TMP_HOME/.local/bin/token-diet-install.sh" ]
  [ -f "$TMP_HOME/.local/bin/lib/hosts.sh" ]

  # Source the installed lib the way the installed installer does, and confirm
  # the registry is actually populated rather than merely present.
  run bash -c "cd '$TMP_HOME/.local/bin' && source ./lib/hosts.sh && td_host_slugs | wc -l | tr -d ' '"
  [ "$status" -eq 0 ]
  [ "$output" = "7" ]

  run bash "$TMP_HOME/.local/bin/token-diet-install.sh" --verify
  [ "$status" -eq 0 ]
  [[ "$output" != *"No such file"* ]]
  [[ "$output" != *"hosts.sh"* ]]
}

# ---------------------------------------------------------------------------
# Cycle 10 — the version-compat gate must survive installation
#
# scripts/token-diet reads config/compat.json at $SCRIPT_DIR/../config/. When
# installed to $HOME/.local/bin, that resolves to $HOME/.local/config/compat.json,
# which the installer never created — so _compat_min always returned "0.0.0"
# and the whole compat gate was a dead no-op on every installed system. Same
# decoupling-omission class as cmd_extract (v1.14.0) and the release.sh crash.
# ---------------------------------------------------------------------------

@test "install: compat.json is copied so the installed compat gate is not dead" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  # token-diet reads $SCRIPT_DIR/../config/compat.json; installed SCRIPT_DIR is
  # $HOME/.local/bin, so the file must land at $HOME/.local/config/compat.json.
  [ -f "$TMP_HOME/.local/config/compat.json" ]

  # And it must carry a real floor, not be empty — prove the gate can read it.
  run python3 -c "import json;print(json.load(open('$TMP_HOME/.local/config/compat.json'))['tools']['rtk']['min'])"
  [ "$status" -eq 0 ]
  [ "$output" != "0.0.0" ]
  [ -n "$output" ]

  # ICM is the fourth tool and must be gated too (was absent).
  run python3 -c "import json;print('icm' in json.load(open('$TMP_HOME/.local/config/compat.json'))['tools'])"
  [ "$output" = "True" ]
}

@test "uninstall: removes the installed compat.json" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]
  [ -f "$TMP_HOME/.local/config/compat.json" ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.local/config/compat.json" ]
}

# ---------------------------------------------------------------------------
# Cycle 10b — the canonical MCP-host registry must survive installation
#
# token-diet-dashboard reads config/hosts-mcp.json at $SCRIPT_DIR/../config/.
# Installed SCRIPT_DIR is $HOME/.local/bin, so the file must land at
# $HOME/.local/config/hosts-mcp.json or host detection has no data source on
# every installed system. Same decoupling-omission class as compat.json.
# ---------------------------------------------------------------------------

@test "install: hosts-mcp.json is copied so the installed dashboard has host data" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude

  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]

  # Dashboard reads $SCRIPT_DIR/../config/hosts-mcp.json; installed SCRIPT_DIR is
  # $HOME/.local/bin, so the file must land at $HOME/.local/config/hosts-mcp.json.
  [ -f "$TMP_HOME/.local/config/hosts-mcp.json" ]

  # It must carry the six-host set, not be empty — prove the dashboard can read it.
  run python3 -c "import json;print(len(json.load(open('$TMP_HOME/.local/config/hosts-mcp.json'))['all_hosts']))"
  [ "$status" -eq 0 ]
  [ "$output" = "6" ]

  # The MCP-key dialect order must be present.
  run python3 -c "import json;print(json.load(open('$TMP_HOME/.local/config/hosts-mcp.json'))['mcp_key_dialect'][0])"
  [ "$output" = "mcpServers" ]
}

@test "uninstall: removes the installed hosts-mcp.json" {
  mock_install_prereqs
  mock_icm
  mock_cmd claude
  run bash "$SCRIPTS_DIR/install.sh" --icm-only
  [ "$status" -eq 0 ]
  [ -f "$TMP_HOME/.local/config/hosts-mcp.json" ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]
  [ ! -f "$TMP_HOME/.local/config/hosts-mcp.json" ]
}

# ---------------------------------------------------------------------------
# Cycle 11 — the default (network) install pins to the audited fork revisions
#
# The default install ran `cargo install --git <repo> --force` and
# `uvx --from git+<repo>` with no revision, floating to upstream HEAD — so a
# default install did NOT match the pinned/audited forks/ submodules or
# compat.json's "tested" versions. The pin is derived from the superproject
# gitlink (single source of truth), never duplicated.
# ---------------------------------------------------------------------------

@test "install: default cargo installs pin --rev to the submodule gitlink" {
  local rtk_rev tilth_rev icm_rev
  rtk_rev="$(git -C "$SCRIPTS_DIR/.." rev-parse 'HEAD:forks/rtk')"
  tilth_rev="$(git -C "$SCRIPTS_DIR/.." rev-parse 'HEAD:forks/tilth')"
  icm_rev="$(git -C "$SCRIPTS_DIR/.." rev-parse 'HEAD:forks/icm')"

  run bash "$SCRIPTS_DIR/install.sh" --dry-run
  [ "$status" -eq 0 ]

  [[ "$output" == *"cargo install --git https://github.com/artificemachine/rtk --rev $rtk_rev"* ]]
  [[ "$output" == *"cargo install --git https://github.com/artificemachine/tilth --rev $tilth_rev"* ]]
  [[ "$output" == *"--rev $icm_rev"* ]]
}

@test "install: default serena launcher pins the uvx git ref" {
  local serena_rev
  serena_rev="$(git -C "$SCRIPTS_DIR/.." rev-parse 'HEAD:forks/serena')"

  run bash "$SCRIPTS_DIR/install.sh" --dry-run
  [ "$status" -eq 0 ]

  # Every serena uvx ref must carry @<rev>, none may be the bare floating ref.
  [[ "$output" == *"git+https://github.com/artificemachine/serena@$serena_rev"* ]]
  [[ "$output" != *"git+https://github.com/artificemachine/serena serena"* ]]
}

# ---------------------------------------------------------------------------
# Phase 5 Iteration 4 — resolve_cowork_cfg reads config paths from the
# canonical MCP-host registry (config/hosts-mcp.json) instead of hardcoding
# the Claude Desktop paths. Converges ONE bash consumer of the config-path
# data onto the registry (Stage 6 HIGH #1: config-path drift).
# ---------------------------------------------------------------------------

@test "hosts.sh: td_host_config_paths returns a host's config paths in registry order" {
  source "$SCRIPTS_DIR/lib/hosts.sh"
  local reg="$TMP_HOME/reg.json"
  cat > "$reg" <<'JSON'
{ "home_configs": [
  { "path": "SENTINEL/mac.json",       "host": "claude-desktop", "format": "json" },
  { "path": ".claude/settings.json",   "host": "claude-code",    "format": "json" },
  { "path": "SENTINEL/linux.json",     "host": "claude-desktop", "format": "json" }
]}
JSON
  run td_host_config_paths "$reg" claude-desktop
  [ "$status" -eq 0 ]
  [ "${#lines[@]}" -eq 2 ]
  # Order preserved; interleaved other-host entries filtered out.
  [ "${lines[0]}" = "SENTINEL/mac.json" ]
  [ "${lines[1]}" = "SENTINEL/linux.json" ]
}

@test "hosts.sh: td_host_config_paths fails (no output) when the registry is absent" {
  source "$SCRIPTS_DIR/lib/hosts.sh"
  run td_host_config_paths "$TMP_HOME/does-not-exist.json" claude-desktop
  [ "$status" -ne 0 ]
  [ -z "$output" ]
}

@test "hosts.sh: td_host_config_paths fails (no output) for a host with no entries" {
  source "$SCRIPTS_DIR/lib/hosts.sh"
  local reg="$TMP_HOME/reg.json"
  cat > "$reg" <<'JSON'
{ "home_configs": [ { "path": ".claude/settings.json", "host": "claude-code", "format": "json" } ] }
JSON
  run td_host_config_paths "$reg" claude-desktop
  [ "$status" -ne 0 ]
  [ -z "$output" ]
}

# ---------------------------------------------------------------------------
# Phase 5 Iteration 5 — detect_hosts found/not-found REPORTING is registry-driven
#
# Characterization guard for the lowest-blast-radius enumeration site. The
# reporting block must stay BYTE-IDENTICAL after being converted from seven
# hardcoded `if $HAS_* ...` lines to a loop over the host registry. The dotted
# alignment ("Claude Code ....." / the two-space "Cowork (Desktop)  ") is the
# fragile part: every label is padded to a fixed column, and Cowork's label is
# exactly wide enough to carry zero dots. These tests pin every dot.
#
# Detection is made deterministic and machine-independent by restricting PATH to
# the sandbox bin plus system dirs, then mocking exactly the hosts we want
# "found". The detection block's found lines say "found"; the later verify block
# says "available", so asserting the contiguous "... found" block targets the
# reporting site unambiguously.
# ---------------------------------------------------------------------------

# PATH the installer sees: mocked bins first, then real system dirs for
# coreutils/python3/uname. Real host binaries (claude, codex, ...) live in
# $HOME/.local/bin or Homebrew and are therefore invisible unless we mock them.
# Computed per-test: $TMP_BIN is only set once setup() has run.
td_test_host_path() { printf '%s' "$TMP_BIN:/usr/bin:/bin:/usr/sbin:/sbin"; }

@test "install.sh: detect_hosts reporting is byte-identical (all seven found)" {
  mock_install_prereqs
  # Mock every host so all seven report "found". Cowork keys off claude-desktop.
  mock_cmd claude
  mock_cmd codex
  mock_cmd opencode
  mock_cmd copilot
  mock_cmd code
  mock_cmd gemini
  mock_cmd claude-desktop

  run env PATH="$(td_test_host_path)" bash "$SCRIPTS_DIR/install.sh" \
    --serena-only --dry-run </dev/null
  [ "$status" -eq 0 ]

  # Contiguous, ordered, byte-exact. All-"found" only appears in the detection
  # block (verify prints "available"), so this pins the reporting site alone.
  local expected
  expected="[ok]    Claude Code ..... found
[ok]    Codex CLI ....... found
[ok]    OpenCode ........ found
[ok]    Copilot CLI ..... found
[ok]    VS Code ......... found
[ok]    Cowork (Desktop)  found
[ok]    Gemini CLI ...... found"
  [[ "$output" == *"$expected"* ]]
}

@test "install.sh: detect_hosts reporting is byte-identical (partial, not-found dots)" {
  mock_install_prereqs
  # Only Claude and Gemini present; the middle five report "not found" — this
  # exercises the dotted not-found lines and the two-space "Cowork (Desktop)".
  mock_cmd claude
  mock_cmd gemini

  run env PATH="$(td_test_host_path)" bash "$SCRIPTS_DIR/install.sh" \
    --serena-only --dry-run </dev/null
  [ "$status" -eq 0 ]

  # Mixed ok/warn contiguous block. Claude says "found" here vs "available" in
  # the verify block, so the whole block only matches the detection site.
  local expected
  expected="[ok]    Claude Code ..... found
[warn]  Codex CLI ....... not found
[warn]  OpenCode ........ not found
[warn]  Copilot CLI ..... not found
[warn]  VS Code ......... not found
[warn]  Cowork (Desktop)  not found
[ok]    Gemini CLI ...... found"
  [[ "$output" == *"$expected"* ]]
}

@test "install.sh: resolve_cowork_cfg derives the Cowork path from the registry" {
  mock_install_prereqs
  # A distinctive Claude Desktop path only the registry knows about.
  local reg="$TMP_HOME/hosts-mcp.json"
  cat > "$reg" <<'JSON'
{ "home_configs": [
  { "path": ".claude/settings.json",              "host": "claude-code",    "format": "json" },
  { "path": "sentinel-cowork/mac-desktop.json",   "host": "claude-desktop", "format": "json" },
  { "path": "sentinel-cowork/linux-desktop.json", "host": "claude-desktop", "format": "json" }
]}
JSON
  # Force HAS_COWORK true without a config file present, so the cowork dry-run
  # write branch runs and prints "... to $COWORK_CFG".
  mock_cmd claude-desktop
  TD_HOSTS_MCP_REGISTRY="$reg" run bash "$SCRIPTS_DIR/install.sh" \
    --serena-only --hosts cowork --dry-run
  [ "$status" -eq 0 ]
  # Neither sentinel file exists, so resolve_cowork_cfg falls to the uname
  # default: the mac path on Darwin, the linux path elsewhere. Either proves the
  # path came from the registry, not the hardcoded Library/... default.
  [[ "$output" == *"sentinel-cowork/"*"-desktop.json"* ]]
  [[ "$output" != *"Library/Application Support/Claude/claude_desktop_config.json"* ]]
}

# ---------------------------------------------------------------------------
# Cycle 7.x — uninstall.sh: MCP-removal path list driven from hosts-mcp.json
# (Phase 5 Iteration 7 — converge the last hard config-path-drift consumer)
# ---------------------------------------------------------------------------

@test "uninstall.sh derives Claude Desktop MCP-removal paths from the registry" {
  # A registry whose claude-desktop macOS path only the registry knows about.
  local reg="$TMP_HOME/hosts-mcp.json"
  cat > "$reg" <<'JSON'
{ "home_configs": [
  { "path": ".claude/settings.json",                     "host": "claude-code",    "format": "json" },
  { "path": "sentinel-desktop/mac.json",                 "host": "claude-desktop", "format": "json" },
  { "path": ".config/Claude/claude_desktop_config.json", "host": "claude-desktop", "format": "json" },
  { "path": ".codex/config.toml",                        "host": "codex",          "format": "text" }
]}
JSON
  # Plant the sentinel desktop config so its removal prints a dry line.
  mkdir -p "$TMP_HOME/sentinel-desktop"
  echo '{"mcpServers":{"icm":{"command":"icm"}}}' > "$TMP_HOME/sentinel-desktop/mac.json"

  TD_HOSTS_MCP_REGISTRY="$reg" run bash "$SCRIPTS_DIR/uninstall.sh" --dry-run --force
  [ "$status" -eq 0 ]
  # The macOS Claude Desktop removal must target the registry path, not the
  # hardcoded Library/... default.
  [[ "$output" == *"sentinel-desktop/mac.json"* ]]
  [[ "$output" != *"Library/Application Support/Claude/claude_desktop_config.json"* ]]
}

@test "uninstall.sh derives the Codex MCP-removal path from the registry" {
  local reg="$TMP_HOME/hosts-mcp.json"
  cat > "$reg" <<'JSON'
{ "home_configs": [
  { "path": ".claude/settings.json", "host": "claude-code", "format": "json" },
  { "path": "sentinel-codex/cfg.toml", "host": "codex", "format": "text" }
]}
JSON
  mkdir -p "$TMP_HOME/sentinel-codex"
  printf '[mcp_servers.icm]\ncommand = "icm"\n' > "$TMP_HOME/sentinel-codex/cfg.toml"

  TD_HOSTS_MCP_REGISTRY="$reg" run bash "$SCRIPTS_DIR/uninstall.sh" --dry-run --force
  [ "$status" -eq 0 ]
  [[ "$output" == *"sentinel-codex/cfg.toml"* ]]
  [[ "$output" != *".codex/config.toml"* ]]
}

@test "uninstall.sh DOES clean .claude.json and gemini MCP keys (Phase 5 symmetry), preserving unrelated servers" {
  # Behavior change (Phase 5 DECISION 2): install writes token-diet's MCP servers
  # to $HOME/.claude.json (via `claude mcp add --scope user`) and to
  # $HOME/.gemini/settings.json (via `gemini mcp add --scope user`). Uninstall must be
  # symmetric and remove them. It must NOT touch a user's own unrelated servers.
  echo '{"mcpServers":{"user-server":{"command":"x"},"tilth":{},"serena":{},"icm":{}}}' > "$TMP_HOME/.claude.json"
  mkdir -p "$TMP_HOME/.gemini"
  echo '{"mcpServers":{"user-server":{"command":"y"},"tilth":{},"serena":{},"icm":{}}}' > "$TMP_HOME/.gemini/settings.json"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  # token-diet's three servers gone from BOTH files; the user's own server stays.
  python3 - "$TMP_HOME/.claude.json" << 'PY'
import json, sys
s = json.load(open(sys.argv[1])).get("mcpServers", {})
for k in ("tilth", "serena", "icm"):
    assert k not in s, f".claude.json still has {k}"
assert "user-server" in s, "unrelated .claude.json server was removed!"
PY
  python3 - "$TMP_HOME/.gemini/settings.json" << 'PY'
import json, sys
s = json.load(open(sys.argv[1])).get("mcpServers", {})
for k in ("tilth", "serena", "icm"):
    assert k not in s, f"gemini still has {k}"
assert "user-server" in s, "unrelated gemini server was removed!"
PY
}

# ---------------------------------------------------------------------------
# Phase 5 FINAL — install/uninstall symmetry (DECISION 2)
#
# ROUND-TRIP PROOF: for each host, capture a config that already holds unrelated
# user content, run the real install path, run uninstall, and assert the config
# is restored — token-diet's own blocks fully removed, every pre-existing user
# key/value preserved. Deep-equality on the parsed structure is the proof that
# uninstall removes EXACTLY what install writes (no more, no less). For the
# direct-write hosts (opencode, codex, cowork/Claude-Desktop) install.sh mutates
# the file itself, so this is a true install->uninstall round-trip. For the
# external-CLI hosts (gemini, claude-code's $HOME/.claude.json) the real host CLI does
# the write, so we plant the realistic post-install state (documented) and prove
# uninstall removes exactly it while preserving unrelated servers.
# ---------------------------------------------------------------------------

@test "symmetry: opencode round-trip — install then uninstall restores the config exactly" {
  mock_install_prereqs
  mock_icm
  mock_cmd opencode

  local cfg="$TMP_HOME/.config/opencode/opencode.json"
  mkdir -p "$(dirname "$cfg")"
  mkdir -p "$TMP_HOME/.config/opencode/plugins"
  # Pre-existing user content in EVERY container install touches: mcp, mode
  # prompts, and the plugin array. Snapshot it, then require byte-for-value restore.
  python3 -c "
import json
d = {
  'mcp': {'user-tool': {'type': 'local', 'command': ['user'], 'enabled': True}},
  'mode': {'build': {'prompt': 'USER BUILD PROMPT'}, 'plan': {'prompt': 'USER PLAN PROMPT'}},
  'plugin': ['./plugins/user.ts'],
}
open('$cfg','w').write(json.dumps(d, indent=2) + '\n')
open('$TMP_HOME/pre.json','w').write(json.dumps(d, sort_keys=True))
"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --icm-only --with-context-hooks --hosts opencode
  [ "$status" -eq 0 ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  python3 - "$cfg" "$TMP_HOME/pre.json" << 'PY'
import json, sys
after = json.load(open(sys.argv[1]))
pre = json.loads(open(sys.argv[2]).read())
assert after == pre, f"opencode not restored.\n after={json.dumps(after,indent=2,sort_keys=True)}\n pre={json.dumps(pre,indent=2,sort_keys=True)}"
PY
  # The token-diet plugin file must also be gone (install wrote it).
  [ ! -f "$TMP_HOME/.config/opencode/plugins/token-diet-hooks.ts" ]
}

@test "symmetry: codex round-trip — uninstall removes every token-diet block, keeps user blocks" {
  mock_install_prereqs
  mock_icm
  mock_cmd codex

  # Pre-existing user MCP block. install APPENDS its blocks after it, so the
  # regex removal (which stops at the next '[') can never eat user content.
  cat > "$TMP_HOME/.codex/config.toml" << 'TOML'
# user's own codex config
[mcp_servers.user-tool]
command = "user-cmd"
args = ["--flag"]
TOML

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --icm-only --hosts codex
  [ "$status" -eq 0 ]
  # sanity: install actually wrote token-diet's blocks
  grep -Eq '^\[mcp_servers\.serena\]'     "$TMP_HOME/.codex/config.toml"
  grep -Eq '^\[mcp_servers\.icm\]'        "$TMP_HOME/.codex/config.toml"
  grep -Eq '^\[mcp_servers\.token-diet\]' "$TMP_HOME/.codex/config.toml"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  # All assertions in ONE python block (the decisive, set -e-caught last command):
  # every token-diet block AND its orphan body lines gone; user block byte-intact.
  python3 - "$TMP_HOME/.codex/config.toml" << 'PY'
import re, sys
text = open(sys.argv[1]).read()
# No token-diet table headers survive.
for name in ("tilth", "serena", "icm", "token-diet"):
    assert not re.search(r'(?m)^\[mcp_servers\.%s\]' % re.escape(name), text), f"{name} header survived:\n{text}"
# No orphaned token-diet body lines survive (the old regex left `["--from",...]`
# and `["serve","--compact"]` arrays and stray "added by token-diet" comments).
assert "start-mcp-server" not in text, f"orphan serena args survived:\n{text}"
assert "serve" not in text or "compact" not in text, f"orphan icm args survived:\n{text}"
assert "token-diet-mcp" not in text, f"token-diet command survived:\n{text}"
assert "added by token-diet" not in text, f"token-diet comment survived:\n{text}"
# User block intact.
assert re.search(r'(?m)^\[mcp_servers\.user-tool\]', text), f"user block lost:\n{text}"
assert re.search(r'(?m)^command = "user-cmd"', text), f"user command lost:\n{text}"
assert re.search(r'(?m)^args = \["--flag"\]', text), f"user args lost:\n{text}"
PY
}

@test "symmetry: cowork/Claude-Desktop round-trip — install then uninstall restores the config exactly" {
  mock_install_prereqs
  mock_cmd tilth   # cowork tilth registration is gated on check_command tilth

  local cowork_dir
  if [ "$(uname -s)" = "Darwin" ]; then
    cowork_dir="$TMP_HOME/Library/Application Support/Claude"
  else
    cowork_dir="$TMP_HOME/.config/Claude"
  fi
  mkdir -p "$cowork_dir"
  local cfg="$cowork_dir/claude_desktop_config.json"
  python3 -c "
import json
d = {'mcpServers': {'user-server': {'command': 'keep-me'}}}
open('$cfg','w').write(json.dumps(d, indent=2) + '\n')
open('$TMP_HOME/pre.json','w').write(json.dumps(d, sort_keys=True))
"

  run bash "$SCRIPTS_DIR/install.sh" --serena-only --icm-only --hosts cowork
  [ "$status" -eq 0 ]

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  python3 - "$cfg" "$TMP_HOME/pre.json" << 'PY'
import json, sys
after = json.load(open(sys.argv[1]))
pre = json.loads(open(sys.argv[2]).read())
assert after == pre, f"cowork not restored.\n after={json.dumps(after,indent=2,sort_keys=True)}\n pre={json.dumps(pre,indent=2,sort_keys=True)}"
PY
}

@test "symmetry: gemini — uninstall removes MCP keys, hooks, token-diet.md and GEMINI.md ref" {
  # Plant the realistic post-install state the real `gemini mcp add` + context
  # hooks + doc writer leave behind, plus unrelated user content that must survive.
  mkdir -p "$TMP_HOME/.gemini"
  local dcmd="$TMP_HOME/.local/bin/token-diet-hooks/docextract-pre-read.sh"
  local ccmd="$TMP_HOME/.local/bin/token-diet-hooks/ctxwarn-post.sh"
  python3 -c "
import json
d = {
  'mcpServers': {'user-server': {'command': 'x'}, 'tilth': {}, 'serena': {}, 'icm': {}},
  'hooks': {
    'PreToolUse': [
      {'matcher': '*', 'hooks': [{'type':'command','command':'echo user','timeout':5}]},
      {'matcher': 'read_file', 'hooks': [{'type':'command','command':'$dcmd','timeout':15}]},
    ],
    'PostToolUse': [
      {'matcher': '*', 'hooks': [{'type':'command','command':'$ccmd','timeout':15}]},
    ],
  },
}
open('$TMP_HOME/.gemini/settings.json','w').write(json.dumps(d, indent=2) + '\n')
"
  echo '# token-diet' > "$TMP_HOME/.gemini/token-diet.md"
  printf 'user rules line\n@token-diet.md\n' > "$TMP_HOME/.gemini/GEMINI.md"

  run bash "$SCRIPTS_DIR/uninstall.sh" --force
  [ "$status" -eq 0 ]

  [ ! -f "$TMP_HOME/.gemini/token-diet.md" ]

  python3 - "$TMP_HOME/.gemini/settings.json" "$dcmd" "$ccmd" "$TMP_HOME/.gemini/GEMINI.md" << 'PY'
import json, sys
d = json.load(open(sys.argv[1]))
dcmd, ccmd = sys.argv[2], sys.argv[3]
gemini_md = open(sys.argv[4]).read()
assert "@token-diet.md" not in gemini_md, "GEMINI.md still references @token-diet.md"
assert "user rules line" in gemini_md, "GEMINI.md user content lost"
s = d.get("mcpServers", {})
for k in ("tilth", "serena", "icm"):
    assert k not in s, f"gemini still has mcp {k}"
assert "user-server" in s, "unrelated gemini server removed!"
# token-diet hook entries gone; the user's PreToolUse/* hook survives.
pre = d.get("hooks", {}).get("PreToolUse", [])
post = d.get("hooks", {}).get("PostToolUse", [])
assert not any(h.get("command") == dcmd for e in pre for h in e.get("hooks", [])), "docextract gemini hook not removed"
assert not any(h.get("command") == ccmd for e in post for h in e.get("hooks", [])), "ctxwarn gemini hook not removed"
assert any(h.get("command") == "echo user" for e in pre for h in e.get("hooks", [])), "user gemini hook removed!"
PY
}
